name: Build Docker

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Log into registry ${{ env.REGISTRY }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login -u "${{ github.actor }}" --password-stdin ${{ env.REGISTRY }}

      - name: Normalize image name
        id: name
        run: |
          NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Build and push OCI image
        run: |
          buildah manifest create drasl

          for system in 'x86_64-linux' 'aarch64-linux'; do
            oci_archive="$(nix build --no-link --print-out-paths ".#oci-cross-$system")"
            buildah manifest add drasl "docker-archive:$oci_archive"
          done

          buildah manifest push --all -f v2s2 drasl "docker://${{ env.REGISTRY }}/${{ steps.name.outputs.name }}:latest"
